server_tokens off;

server {
    listen 8080 default_server;
    server_name _;

    access_log off;
    error_log /dev/stderr crit;

    location / {
        default_type text/plain;
        add_header Cache-Control "no-store" always;
        return 403 "Forbidden\n";
    }
}