from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "servidor/api-internal"))
from app.assistant_sql import SqlPolicyError, default_has_side_effects, inspect_sql


class AssistantSqlPolicyTest(unittest.TestCase):
    def test_row_events_are_distinct_from_ddl_and_foreign_key_references(self):
        self.assertEqual(inspect_sql("CREATE INDEX child_id_idx ON public.child(id)").row_events, ())
        self.assertEqual(inspect_sql("CREATE TABLE public.child(id bigint REFERENCES public.parent(id))").row_events, ())
        self.assertEqual(inspect_sql("UPDATE public.child SET id=2").row_events, (("child", 16),))
        self.assertEqual(inspect_sql("WITH inserted AS (INSERT INTO public.child VALUES(1) RETURNING id) SELECT 1").row_events, (("child", 4),))
        self.assertEqual(inspect_sql("ALTER TABLE public.child ADD CONSTRAINT positive CHECK(id>0)").validates, ("child",))

    def test_create_insert_update_and_bounded_select_are_not_deletions(self):
        for sql in (
            "CREATE TABLE public.items(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text NOT NULL)",
            "INSERT INTO public.items(title) VALUES ('DELETE is only a string')",
            "UPDATE public.items SET title='DROP TABLE' WHERE id=1",
            "SELECT count(*), max(id) FROM public.items",
            "CREATE INDEX items_id ON public.items(id)",
            "ALTER TABLE public.items ADD COLUMN note text",
            "CREATE TABLE public.child(id integer, parent_id bigint REFERENCES public.items(id))",
        ):
            with self.subTest(sql=sql):
                self.assertFalse(inspect_sql(sql).destructive)

    def test_every_delete_and_destructive_ddl_requires_explicit_approval(self):
        for sql in (
            "DELETE FROM public.items WHERE id=1", "delete from public.items",
            "/* UPDATE */ DELETE FROM public.items WHERE false",
            "WITH gone AS (DELETE FROM public.items RETURNING id) SELECT 1",
            "TRUNCATE TABLE public.items", "DROP TABLE public.items",
            "ALTER TABLE public.items DROP COLUMN title",
            "ALTER TABLE public.items DROP CONSTRAINT items_pkey",
            "ALTER TABLE public.items ALTER COLUMN id TYPE text",
        ):
            with self.subTest(sql=sql):
                self.assertTrue(inspect_sql(sql).destructive)

    def test_fail_closed_for_cluster_schemas_code_functions_and_batches(self):
        for sql in (
            "UPDATE public.items SET id=2; DELETE FROM public.items", "", "not SQL",
            "CREATE ROLE stolen SUPERUSER", "SET ROLE postgres", "GRANT ALL ON public.items TO PUBLIC",
            "COPY public.items TO PROGRAM 'true'", "DO $$ BEGIN DELETE FROM public.items; END $$",
            "SELECT pg_catalog.lo_unlink(1)", "SELECT public.delete_all()", "CALL public.delete_all()",
            "SELECT pg_catalog.set_config('search_path','public',false)",
            "SELECT * FROM auth.users", "SELECT * FROM pg_catalog.pg_authid",
            "CREATE TABLE auth.stolen(id integer)", "CREATE TABLE public.child(id uuid REFERENCES auth.users(id))",
            "CREATE TEMP TABLE public.items(id integer)", "DROP TABLE public.items CASCADE",
            "TRUNCATE public.items CASCADE", "ALTER TABLE public.items OWNER TO postgres",
            "ALTER TABLE public.items DISABLE ROW LEVEL SECURITY", "CREATE VIEW public.items AS SELECT 1",
            "CREATE TABLE public.items(id public.custom_type)", "SELECT 'x'::public.custom_type",
            "SELECT * INTO public.items FROM public.other", "SELECT * FROM public.items FOR UPDATE",
            "SELECT * FROM items", "SELECT 1 OPERATOR(public.+) 2",
            "CREATE INDEX items_idx ON public.items(id public.custom_ops)",
            "SELECT * FROM public.items TABLESAMPLE public.custom_sampler(1)",
            "SELECT id FROM public.items ORDER BY id USING OPERATOR(public.<)",
            "SELECT XMLPARSE(DOCUMENT '<data/>')",
        ):
            with self.subTest(sql=sql):
                with self.assertRaises(SqlPolicyError):
                    inspect_sql(sql)

    def test_relations_include_nested_queries_and_foreign_key_targets(self):
        plan = inspect_sql("CREATE TABLE public.child(id integer REFERENCES public.parent(id))")
        self.assertEqual(plan.relations, ("child", "parent"))
        self.assertEqual(plan.creates, ("child",))
        plan = inspect_sql("UPDATE public.items SET id=(SELECT max(id) FROM public.other)")
        self.assertEqual(plan.relations, ("items", "other"))
        self.assertTrue(plan.writes)
        self.assertTrue(inspect_sql("WITH changed AS (UPDATE public.items SET id=1 RETURNING id) SELECT 1").writes)

    def test_default_functions_are_not_assumed_safe_even_when_they_are_builtin(self):
        self.assertFalse(default_has_side_effects("now()"))
        self.assertFalse(default_has_side_effects("nextval('public.items_id_seq'::regclass)"))
        self.assertTrue(default_has_side_effects("public.delete_items()"))
        self.assertTrue(default_has_side_effects("lo_unlink(42)"))
        self.assertTrue(default_has_side_effects("1 OPERATOR(public.+) 2"))
