#docker compose --env-file ../secrets/.env --env-file ../.env --env-file .env up -d
services:
  nginx:
    image: openresty/openresty:1.21.4.1-0-alpine
    container_name: nginx
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      - rede-supabase
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
  studio:
    container_name: supabase-studio
    image: supabase/studio:20250324-13e75a5
    restart: unless-stopped
    env_file:
      - ../secrets/.env
      - .env
    networks:
      - rede-supabase
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://studio:3000/api/profile').then((r) => {if (r.status !== 200) throw new Error(r.status)})"
        ]
      timeout: 10s
      interval: 5s
      retries: 3
    environment:
      # STUDIO_PG_META_URL: http://meta:8080
      STUDIO_PG_META_URL: http://nginx:4000/api/platform/pg-meta
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DB}
      DEFAULT_PROJECT_NAME: ${STUDIO_DB}
      OPENAI_API_KEY: 
      SUPABASE_URL: http://rest:3000
      SUPABASE_PUBLIC_URL: http://<SEU_IP>:4000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}
      # AUTH_JWT_SECRET: ${JWT_SECRET_STUDIO}
      NEXT_PUBLIC_ENABLE_LOGS: false
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
  
  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.88.7
    restart: unless-stopped
    networks:
      - rede-supabase
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: 172.20.200.10
      PG_META_DB_PORT: 6755
      PG_META_DB_NAME: ${STUDIO_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  # analytics:
  #   container_name: supabase-analytics
  #   image: supabase/logflare:1.12.0
  #   restart: unless-stopped
  #   networks:
  #     - rede-supabase
  #   ports:
  #     - 8080:4000
  #   # Uncomment to use Big Query backend for analytics
  #   # volumes:
  #   #   - type: bind
  #   #     source: ${PWD}/gcloud.json
  #   #     target: /opt/app/rel/logflare/bin/gcloud.json
  #   #     read_only: true
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "curl",
  #         "http://localhost:4000/health"
  #       ]
  #     timeout: 5s
  #     interval: 5s
  #     retries: 10
  #   environment:
  #     LOGFLARE_NODE_HOST: 127.0.0.1
  #     DB_USERNAME: supabase_admin
  #     DB_DATABASE: ${STUDIO_DB}
  #     DB_HOSTNAME: ${POSTGRES_HOST}
  #     DB_PORT: ${POSTGRES_PORT}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     DB_SCHEMA: _analytics
  #     LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
  #     LOGFLARE_SINGLE_TENANT: true
  #     LOGFLARE_SUPABASE_MODE: true
  #     LOGFLARE_MIN_CLUSTER_SIZE: 1
  #     # Comment variables to use Big Query backend for analytics
  #     POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${STUDIO_DB}
  #     POSTGRES_BACKEND_SCHEMA: _analytics
  #     LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true
  #     # Uncomment to use Big Query backend for analytics
  #     # GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
  #     # GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}

networks:
  rede-supabase:
    external: true