// Generated by tools/generate_identity_models.py.

const canonicalUuidPattern = r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
const projectNamePattern = r'^[a-z_][a-z0-9_]{2,39}$';
const publicRefPattern = r'^[a-z]{20}$';
class ProjectIdentity {
  const ProjectIdentity({
    required this.projectUuid,
    required this.tenantUuid,
    required this.name,
    required this.publicRef,
    required this.displayName,
  });

  final String projectUuid;
  final String? tenantUuid;
  final String name;
  final String publicRef;
  final String displayName;

  factory ProjectIdentity.fromJson(Map<String, dynamic> json) {
    for (final key in <String>['project_uuid', 'tenant_uuid', 'name', 'public_ref', 'display_name']) {
      if (!json.containsKey(key)) throw FormatException('Identidade ausente: $key');
    }
    return ProjectIdentity(
      projectUuid: _identityText(json, 'project_uuid', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36)!,
      tenantUuid: _identityText(json, 'tenant_uuid', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36, nullable: true),
      name: _identityText(json, 'name', r'^[a-z_][a-z0-9_]{2,39}$', 3, 40)!,
      publicRef: _identityText(json, 'public_ref', r'^[a-z]{20}$', 20, 20)!,
      displayName: _identityText(json, 'display_name', r'\S', 1, 80)!,
    );
  }
}

class JobIdentity {
  const JobIdentity({
    required this.jobId,
    required this.project,
    required this.publicRef,
    required this.projectUuid,
    required this.tenantUuid,
    required this.createdBy,
  });

  final String jobId;
  final String project;
  final String? publicRef;
  final String? projectUuid;
  final String? tenantUuid;
  final String? createdBy;

  factory JobIdentity.fromJson(Map<String, dynamic> json) {
    for (final key in <String>['job_id', 'project', 'public_ref', 'project_uuid', 'tenant_uuid', 'created_by']) {
      if (!json.containsKey(key)) throw FormatException('Identidade ausente: $key');
    }
    return JobIdentity(
      jobId: _identityText(json, 'job_id', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36)!,
      project: _identityText(json, 'project', r'^[a-z_][a-z0-9_]{2,39}$', 3, 40)!,
      publicRef: _identityText(json, 'public_ref', r'^[a-z]{20}$', 20, 20, nullable: true),
      projectUuid: _identityText(json, 'project_uuid', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36, nullable: true),
      tenantUuid: _identityText(json, 'tenant_uuid', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36, nullable: true),
      createdBy: _identityText(json, 'created_by', r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', 36, 36, nullable: true),
    );
  }
}

String? _identityText(Map<String, dynamic> json, String key,
    String pattern, int minimum, int maximum, {bool nullable = false}) {
  final value = json[key];
  if (nullable && value == null) return null;
  if (value is! String || value.runes.length < minimum || value.runes.length > maximum ||
      !RegExp(pattern).hasMatch(value)) {
    throw FormatException('Identidade invalida: $key');
  }
  return value;
}
