services:
  usersdb-init:
    command: ["sh", "/usr/local/bin/initialize-usersdb.sh"]
    volumes:
      - ./initialize-usersdb.sh:/usr/local/bin/initialize-usersdb.sh:ro
  authelia:
    volumes:
      - usersdb:/config
    depends_on:
      usersdb-init:
        condition: service_completed_successfully
  nginx:
    volumes:
      - usersdb:/config
    depends_on:
      usersdb-init:
        condition: service_completed_successfully
