"""Generate the Flutter identity models from the Python API contract."""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "servidor/api-internal"))
from app.identity_schemas import JobIdentity, ProjectIdentity

TARGET = ROOT / "studio/seletor_de_projetos/lib/models/project_identity.dart"


def camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(part.title() for part in tail)


def render() -> str:
    chunks = ["// Generated by tools/generate_identity_models.py.\n"]
    properties = ProjectIdentity.model_json_schema()["properties"]
    for field, name in (("project_uuid", "canonicalUuidPattern"), ("name", "projectNamePattern"), ("public_ref", "publicRefPattern")):
        chunks.append(f"const {name} = r'{properties[field]['pattern']}';")
    for model in (ProjectIdentity, JobIdentity):
        schema = model.model_json_schema()
        fields = []
        parsers = []
        args = []
        for key, raw in schema["properties"].items():
            nullable = "anyOf" in raw
            field = raw["anyOf"][0] if nullable else raw
            if field.get("type") != "string":
                raise ValueError(f"Unsupported identity type: {key}")
            name = camel(key)
            fields.append(f"  final String{'?' if nullable else ''} {name};")
            args.append(f"    required this.{name},")
            pattern = field["pattern"]
            minimum, maximum = field["minLength"], field["maxLength"]
            expression = (f"_identityText(json, '{key}', r'{pattern}', {minimum}, {maximum}"
                          f"{', nullable: true' if nullable else ''})")
            parsers.append(f"      {name}: {expression}{'' if nullable else '!'},")
        required_keys = ", ".join(f"'{key}'" for key in schema["required"])
        chunks.append(f"""class {model.__name__} {{
  const {model.__name__}({{
{chr(10).join(args)}
  }});

{chr(10).join(fields)}

  factory {model.__name__}.fromJson(Map<String, dynamic> json) {{
    for (final key in <String>[{required_keys}]) {{
      if (!json.containsKey(key)) throw FormatException('Identidade ausente: $key');
    }}
    return {model.__name__}(
{chr(10).join(parsers)}
    );
  }}
}}
""")
    chunks.append("""String? _identityText(Map<String, dynamic> json, String key,
    String pattern, int minimum, int maximum, {bool nullable = false}) {
  final value = json[key];
  if (nullable && value == null) return null;
  if (value is! String || value.runes.length < minimum || value.runes.length > maximum ||
      !RegExp(pattern).hasMatch(value)) {
    throw FormatException('Identidade invalida: $key');
  }
  return value;
}
""")
    return "\n".join(chunks)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if TARGET.read_text(encoding="utf-8") != text:
            print("Identity models are out of sync; run tools/generate_identity_models.py")
            return 1
    else:
        TARGET.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
