server:
  address: tcp://0.0.0.0:9091/
  tls:
    certificate: /config/ssl/ca.pem
    key:         /config/ssl/ca.key 

log:
  level: info

#docker run --rm authelia/authelia:4.39 authelia crypto rand --length 64 --charset alphanumeric
identity_validation:
  reset_password:
    jwt_secret: "JWT_SECRET"
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
session:
  cookies:
    - name: authelia_session
      domain: <SEU_IP>       
      authelia_url: https://<SEU_IP>:9091
      default_redirection_url: https://<SEU_IP>:4000
      same_site: lax
  secret: "SESSION_SECRET"
  expiration: '24h'
  inactivity: '3h'
#openssl rand -hex 96
storage:
  local:
    path: /config/db.sqlite3
  encryption_key: "STORAGE_KEY"

authentication_backend:
  file:
    path: /config/users_database.yml
    extra_attributes:
      created_at:
        multi_valued: false
        value_type: string
    watch: true
    search:
      email: true
      case_insensitive: true


access_control:
  default_policy: deny
  rules:
    - domain: "<SEU_IP>"
      policy: one_factor
      subject:
      - ["group:active"]

notifier:
  filesystem:
    filename: /config/notifications.txt

# notifier:
#   smtp:
#     address: 'submission://smtp.gmail.com:587'
#     timeout: '10s'
#     username: 'exemplo'
#     password: 'exemplo'
#     sender: "Exemplo<exemplo@example.com>"
#     identifier: 'exemplo'
#     subject: "[Authelia] {title}"
#     startup_check_address: 'exemplo@example.com'